name: 'f1toolbox'
version: '1.0.0'
config-version: 2

profile: 'f1toolbox'

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

clean-targets:
# directories to be removed by `dbt clean`
- "target"
- "dbt_packages"

data_tests:
  +severity: warn

#https://docs.getdbt.com/docs/configuring-models
models:
  f1toolbox:
    # Config indicated by + and applies to all files under models/<DIRECTORYNAME FROM YAML NAME>/
    #https://docs.getdbt.com/docs/build/materializations
    bronze:
      +materialized: view
      +group: bronze
      +schema: bronze
    silver:
      +materialized: view
      +group: silver
      +schema: silver
    gold:
      +materialized: table
      +group: gold
      +schema: gold
    marts:
      +materialized: table
      +group: marts
      +schema: marts
