f1toolbox:
  #https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: f1toolbox-core
      dataset: f1toolbox_core
      threads: 4 # Must be a value of 1 or greater
