repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        name: Check for files larger than 5 MB
        args: [ "--maxkb=5120" ]
      - id: end-of-file-fixer
        name: Check for a blank line at the end of scripts (auto-fixes)
      - id: trailing-whitespace
        name: Check for trailing whitespaces (auto-fixes)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff-format
        name: ruff formatter
        #exclude: test_example_module.py|run_pipeline.py
      - id: ruff
        args: [ --fix ]
        name: ruff linter
        #exclude: test_example_module.py|run_pipeline.py
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.0
    hooks:
      - id: sqlfluff-fix
        name: sqlfluff-fix
        # Set a couple of default flags:
        #  - `--show-lint-violations` shows issues to not require running `sqlfluff lint`
        #  - `--processes 0` to use maximum parallelism
        # By default, this hook applies all rules.
        entry: sqlfluff fix src/dbt/models --dialect=clickhouse --show-lint-violations --processes 0
        language: python
        description: "Fixes sql lint errors with `SQLFluff`"
        types: [sql]
        require_serial: true
        additional_dependencies: []
