SELECT
    driver AS driver_code,
    time AS session_time_lap_end,
    drivernumber AS driver_number,
    laptime AS lap_time,
    lapnumber AS lap_number,
    stint AS stint_number,
    pitouttime AS pit_out_time,
    pitintime AS pit_in_time,
    sector1time AS sector_1_time,
    sector2time AS sector_2_time,
    sector3time AS sector_3_time,
    sector1sessiontime AS sector_1_session_time,
    sector2sessiontime AS sector_2_session_time,
    sector3sessiontime AS sector_3_session_time,
    speedi1 AS speed_trap_1,
    speedi2 AS speed_trap_2,
    speedfl AS speed_trap_start_finish,
    speedst AS speed_trap_longest_straight,
    ispersonalbest AS is_personal_best,
    compound AS tyre_compound,
    tyrelife AS tyre_age_laps,
    freshtyre AS is_fresh_tyre,
    team AS constructor_name,
    lapstarttime AS lap_start_time,
    lapstartdate AS lap_start_date,
    trackstatus AS track_status,
    position,
    deleted AS is_deleted,
    deletedreason AS deleted_reason,
    fastf1generated AS is_fastf1_generated,
    isaccurate AS is_accurate,
    CAST(session_id AS Nullable(Int64)) AS session_id,
    CAST(event_id AS Nullable(Int64)) AS event_id
FROM FILE('fastf1/laps.parquet', 'Parquet')
