name: 'f1toolbox'
version: '1.0.0'
config-version: 2

profile: 'f1toolbox'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

#https://docs.getdbt.com/docs/configuring-models
models:
  f1toolbox:
    # Config indicated by + and applies to all files under models/silver/
    silver:
    #https://docs.getdbt.com/docs/build/materializations
    #https://clickhouse.com/blog/clickhouse-dbt-project-introduction-and-webinar#model-types
      +materialized: view
    gold:
      +materialized: incremental
