name: ruff-ci
on:
  pull_request:


jobs:
  build:
    name: ruff-ci
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir --upgrade ruff
    - name: Run Ruff Formatter
      run: ruff format
    # Update output format to enable automatic inline annotations.
    - name: Run Ruff Linter
      run: ruff check --fix --output-format=github
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Apply Ruff formatting and linting"
