name: sqlfluff-ci
on:
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:
    name: sqlfluff-ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/dagster/dbt
    steps:
    - uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir --upgrade sqlfluff
    - name: Lint models
      run: "sqlfluff lint models tests --dialect=bigquery"
